name: "nightly"

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read # minimal permissions that we have to grant

jobs:
  Acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.2
          - 2.7

    env:
      RVM_GEM_VERSION: ${{ matrix.ruby_version }}

    steps:
      - run: |
          echo "SANITIZED_RUBY_VERSION=$(echo '${{ matrix.ruby_version }}' | sed 's/~> //g')" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: bundle install
        run: |
          bundle install

      - name: Run Acceptance Tests
        run: |
          bundle exec rake dropsonde:acceptance

