name: "nightly"

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.7

    env:
      RVM_GEM_VERSION: ${{ matrix.ruby_version }}

    steps:
      - run: |
          echo "SANITIZED_RUBY_VERSION=$(echo '${{ matrix.ruby_version }}' | sed 's/~> //g')" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: bundle install
        run: |
          bundle install

      - name: Run Acceptance Tests
        run: |
          bundle exec rake dropsonde:acceptance

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - Acceptance
    runs-on: ubuntu-20.04
    steps:
      - name: Slack Workflow Notification
        uses: puppetlabs/Gamesight-slack-workflow-status@pdk-templates-v1
        with:
          # Required Input
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          # Optional Input
          channel: '#team-ia-bots'
          name: 'GABot'
