name: "Spec Tests"

on:
  workflow_dispatch:
  pull_request:

jobs:
  Spec:
    name: "Spec Tests (Ruby: ${{matrix.ruby_version}})"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.2
          - 2.7

    env:
      RVM_GEM_VERSION: ${{ matrix.ruby_version }}

    steps:
      - run: |
          echo "SANITIZED_RUBY_VERSION=$(echo '${{ matrix.ruby_version }}' | sed 's/~> //g')" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: Run Static & Syntax Tests
        run: |
          bundle exec rubocop

      - name: Run spec tests
        run: |
          bundle exec rake spec

